app/urls.py
from django.urls import path
from django.conf.urls import handler404
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('quiz1/', views.quiz1, name='quiz1'),
    path('quiz2/', views.quiz2, name='quiz2'),
    path('quiz3/', views.quiz3, name='quiz3'),
    path('quiz4/', views.quiz4, name='quiz4'),
    path('quiz5/', views.quiz5, name='quiz5'),
    path('quiz6/', views.quiz6, name='quiz6'),
    path('b_ecoli/', views.b_ecoli, name='b_ecoli'),
    # path('b_lplant/', views.b_lplant, name='b_lplant'),
    path('congrats/', views.congrats, name='congrats'),
    path('update_score/', views.update_score, name='update_score'),
    
    
    path('accounts/login/', views.signin, name='signin'),
    path('logout/', views.signout, name='signout'),
    path('signup/', views.signup, name='signup'),
    path('result/', views.result, name='result'),
]

handler404 = views.custom_404_page

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
# urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

app/forms.py
import random
import string
from django import forms
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.mail import BadHeaderError
from django.conf import settings
import smtplib
from email.message import EmailMessage
import logging
import traceback

logger = logging.getLogger(__name__)


def generate_random_password(length=8):
    characters = string.ascii_lowercase + string.digits
    return ''.join(random.choice(characters) for i in range(length))

def generate_unique_username(first_name):
    base_username = ''.join(filter(str.isalpha, first_name)).lower()
    username = base_username
    while User.objects.filter(username=username).exists():
        username = f"{base_username}{random.randint(1000, 9999)}"
    return username

class SignUpForm(forms.ModelForm):
    full_name = forms.CharField(label="Full Name", max_length=100)
    email = forms.EmailField(label="Email")

    class Meta:
        model = User
        fields = ('full_name', 'email')

    def save(self, commit=True):
        user = super().save(commit=False)
        
        # Store the full name in first_name and leave last_name blank
        user.first_name = self.cleaned_data.get('full_name')
        user.last_name = ''

        user.username = generate_unique_username(user.first_name)
        password = generate_random_password()
        temp_pw = password
        user.set_password(password)
        

        # Inside your save() method:
        if commit:
            user.save()
            try:
                # send_mail(
                #     'Your account credentials',
                #     f'Welcome to NYBB Go!\nUsername: {user.username}\nPassword: {password}',
                #     settings.DEFAULT_FROM_EMAIL,
                #     [self.cleaned_data.get('email')],
                #     fail_silently=False,
                # )
                
               

                # Email credentials
                username = settings.DEFAULT_FROM_EMAIL
                password = settings.EMAIL_HOST_PASSWORD # Replace with the actual password

                # Email content
                msg = EmailMessage()
                msg['Subject'] = 'Your account credentials'
                msg['From'] = username
                msg['To'] = self.cleaned_data.get('email')
                msg.set_content(f'Welcome to NYBB Go!\nUsername: {user.username}\nPassword: {temp_pw}')

                # SMTP server configuration
                smtp_server = 'mail.soash.xyz'
                smtp_port = 465  # SSL port

                # Send the email
                try:
                    with smtplib.SMTP_SSL(smtp_server, smtp_port) as server:
                        server.login(username, password)
                        server.send_message(msg)
                        print('Email sent successfully!')
                except Exception as e:
                    print(f'Failed to send email: {e}')
                
                
                
                
                logger.info(f"Email successfully sent to {self.cleaned_data.get('email')} for user {user.username}")
            except BadHeaderError:
                logger.error("Invalid header found while sending email.")
            except Exception as e:
                logger.error("An error occurred while sending email:")
                logger.error(traceback.format_exc())

templates/b_ecoli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Congrats</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body>    
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>
    <h2 style="color: #e74c3c">Issue 3</h2>

    <div style="text-align: center;">
        <p>Escherichia coli</p>
        <p>Lactobacillus plantarum</p>
    </div>

    <footer><span>&copy; 2024 | </span> <span><a href="#">NYBB - SUST</a></span></footer> 
</body>
</html>

templates/b_lplant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Congrats</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body>    
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>
    <h2 style="color: #e74c3c">Issue 3</h2>

    <div style="text-align: center;">
        <p>Lactobacillus plantarum</p>
    </div>

    <footer><span>&copy; 2024 | </span> <span><a href="#">NYBB - SUST</a></span></footer> 
</body>
</html>

templates/congrats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Congrats</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body>    
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>
    <h2 style="color: #e74c3c">Congratulations</h2>

    <div style="text-align: center;">
        <p>You have completed all the levels!</p>
        <a href="{% url 'index' %}" class="button button-blue" style="display: inline-block;">Home</a>
    </div>

    <footer><span>&copy; 2024 | </span> <span><a href="#">NYBB - SUST</a></span></footer> 
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <style>
        .status {
            display: flex;
            margin-top: 0px;
            gap: 10px;
            flex-wrap: wrap;
            justify-content: center;
            flex-direction: row;
        }
        .div-1 {
            display: flex;
            flex-direction: row;
            align-items: center;
            gap: 10px;
            justify-content: center;
        }
    </style>
</head>
<body>
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>

    <div style="display: flex; flex-direction: column; gap: 25px;">
        <div class="score-board" style="margin-bottom:0px;">
            <span>{{request.user}}</span>
            <span>Score: {{request.user.team.score}}</span>
        </div>
        <div style="display: flex;justify-content: center;">
            <div style="font-size: 0.9rem;">{{request.user.team.log|safe}}</div>
        </div>
        <div class="status">
            {% if request.user.team.quiz_1_status == True %}
                <a href="{% url 'quiz1' %}" class="button button-green">Issue 1: <br> Solved</a>{% else %}
                <a href="{% url 'quiz1' %}" class="button button-red">Issue 1: Unsolved</a>{% endif %}
            {% if request.user.team.quiz_2_status == True %}
                <a href="{% url 'quiz2' %}" class="button button-green">Issue 2: <br> Solved</a>{% else %}
                <a href="{% url 'quiz2' %}" class="button button-red">Issue 2: Unsolved</a>{% endif %}
            {% if request.user.team.quiz_3_status == True %}
                <a href="{% url 'quiz3' %}" class="button button-green">Issue 3: <br> Solved</a>{% else %}
                <a href="{% url 'quiz3' %}" class="button button-red">Issue 3: Unsolved</a>{% endif %}
            {% if request.user.team.quiz_4_status == True %}
                <a href="{% url 'quiz4' %}" class="button button-green">Issue 4: <br> Solved</a>{% else %}
                <a href="{% url 'quiz4' %}" class="button button-red">Issue 4: Unsolved</a>{% endif %}
            {% if request.user.team.quiz_5_status == True %}
                <a href="{% url 'quiz5' %}" class="button button-green">Issue 5: <br> Solved</a>{% else %}
                <a href="{% url 'quiz5' %}" class="button button-red">Issue 5: Unsolved</a>{% endif %}
            {% if request.user.team.quiz_6_status == True %}
                <a href="{% url 'quiz6' %}" class="button button-green">Issue 6: <br> Solved</a>{% else %}
                <a href="{% url 'quiz6' %}" class="button button-red">Issue 6: Unsolved</a>{% endif %}
        </div>
        <div class="div-1">
            {% comment %} <a href="{% url 'signin' %}" class="button button-blue">Sign In</a> {% endcomment %}
            <a href="{% url 'result' %}" class="button button-blue">Result</a>
            <a href="{% url 'signout' %}" class="button button-blue">Sign Out</a>
        </div>    
    </div>

    <footer><span>&copy; 2024 | </span> <span><a href="https://soash.github.io/">NYBB - SUST</a></span></footer>

</body>
</html>

templates/over.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Wait</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="stylesheet" href="{% static 'signin.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body>    
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>

    <div style="text-align: center;">
        <p>The competition Over</p>
    </div>

    <footer><span>&copy; 2024 | </span> <span><a href="#">NYBB - SUST</a></span></footer> 


    
</body>
</html>

templates/quiz1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Issue 1</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body>
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>
    <h2>Issue 1</h2>

    {% if error_message %}
        <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
            <strong>{{error_message}}</strong>
        </div>  
    {% endif %}

    <div class="score-board">
        <span>{{request.user}}</span>
        <span>Score: {{request.user.team.score}}</span>
    </div>

    <div class="clue">
        <div class="clue-1">
            In the year 3024, you as a Biotechnologist, received a distress call from the distant planet Luminescia. 
            Their inhabitants were grappling with a crisis stemming from an autosomal recessive disorder. Dr. Victor Frost had been 
            diligently working on this affliction, primarily affecting the neurological health of the populace. Unfortunately, tragedy 
            struck as Dr. Victor untimely passed away due to unknown circumstances.

            You've been summoned to continue his crucial research, but there's a hurdle. His vital research data is locked within his
            laptop, secured by a four-digit code. Before his demise, Dr. Victor left a cryptic clue, ensuring that only a worthy successor 
            could carry on his work. The clue provided reads:
        </div>
        <div class="clue-2">
            <span>GAC AAT GCA GAC GCA TAT</span>
        </div>
    </div><br>

    <form action="{% url 'quiz1' %}" method="post"> {% csrf_token %}
        <input type="number" name="UnlockKey" min="1000" max="9999" placeholder="C O D E">

        {% if request.user.team.quiz_1_status == False %}
            <button type="submit" class="button button-green">Submit</button>
        {% else %}
            <button type="submit" class="button button-black" disabled>Submit</button>
        {% endif %}
    </form>

    <div class="status">
        {% if request.user.team.quiz_1_status == False %}
            <span>Issue 1: Unsolved</span>
        {% else %}
            <span>Issue 1: Solved</span>
            <a href="{% url 'quiz2' %}" class="button button-red">Issue 2</a>
        {% endif %}
    </div>

    <footer><span>&copy; 2024 | </span> <span><a href="#">NYBB - SUST</a></span></footer>
</body>
</html>

templates/quiz2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Issue 2</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <style>
        .clue-2 a{
            text-decoration: none;
        }        
    </style>
</head>
<body>
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>
    <h2>Issue 2</h2>

    {% if error_message %}
        <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
            <strong>{{error_message}}</strong>
        </div>  
    {% endif %}

    <div class="score-board">
        <span>{{request.user}}</span>
        <span>Score: {{request.user.team.score}}</span>
    </div>

    <div class="clue">
        <div class="clue-1">
            Unlocking the Laptop, a folder called MindCircuit contains a few notes. The note contains some information. 
            “My findings are that. this disease is due to some mutation in a gene located in the autosome. 
            It is an inherited disorder but somehow people of Luminescia are having their genes mutated and 
            it is spreading to the next generation. As you have come this far, it is your duty to find out the 
            reason for this and develop a cure for the people of Luminescia. I  fear someone is trying to stop our research. 
            I've backed up my research and formed several clues. You need to find the location of the gene. I hope you can cure my people. Good luck.
        </div>
        <div class="clue-2">
            <span><a href="{% static 'unknown.txt' %}">unknown.txt</a></span>
        </div>
    </div><br>

    <form action="{% url 'quiz2' %}" method="post"> {% csrf_token %}
        <input type="text" name="UnlockKey" placeholder="Gene Location"> 
        {% if request.user.team.quiz_2_status == False %}
            <button type="submit" class="button button-green">Submit</button>
        {% else %}
            <button type="submit" class="button button-black" disabled>Submit</button>
        {% endif %}
    </form>

    <div class="status">
        {% if request.user.team.quiz_2_status == False %}
            <span>Issue 2: Unsolved</span>
        {% else %}
            <span>Issue 2: Solved</span>
            <a href="{% url 'quiz3' %}" class="button button-red">Issue 3</a>
        {% endif %}
    </div>

    <footer><span>&copy; 2024 | </span> <span><a href="#">NYBB - SUST</a></span></footer>
</body>
</html>

templates/quiz3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Issue 3</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body>
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>
    <h2>Issue 3</h2>
    
    {% if error_message %}
        <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
            <strong>{{error_message}}</strong>
        </div>  
    {% endif %}

    <div class="score-board">
        <span>{{request.user}}</span>
        <span>Score: {{request.user.team.score}}</span>
    </div>

    <div class="clue">
        <div class="clue-1">
            Now that we know the disease is caused by mutations in the PAH gene, 
            resulting in Phenylalanine Hydroxylase deficiency, leading to the accumulation 
            of Phenylalanine in the body, we need to produce and supply it to the body. This will be 
            done using recombinant DNA technology, utilizing bacteria for the production process. 
            Bacteria can be found in the following location:
            <div><br>
                Location 1:<br>
                    With flag held high and book in hand,<br>
                    Two students brave take their stand.<br>
                    A symbol of hope, a nation's plea,<br>
                    What war memorial stands tall and free?<br>
            </div>
            <div>
                <br>
                You will find these bacteria in the location mentioned above:
                <a href="{% url 'b_ecoli' %}">Bacteria</a>
            </div>
            <div class="clue-2">
                <span>Hint: Unlock key is the word value of bacteria</span>
            </div>
        </div>
    </div><br>

    <form action="{% url 'quiz3' %}" method="post"> {% csrf_token %}
        <input type="text" name="UnlockKey" placeholder="Unlock Key"> 
        {% if request.user.team.quiz_3_status == False %}
            <button type="submit" class="button button-green">Submit</button>
        {% else %}
            <button type="submit" class="button button-black" disabled>Submit</button>
        {% endif %}
    </form>

    <div class="status">
        {% if request.user.team.quiz_3_status == False %}
            <span>Issue 3: Unsolved</span>
        {% else %}
            <span>Issue 3: Solved</span>
            <a href="{% url 'quiz4' %}" class="button button-green">Issue 4</a>
        {% endif %}
    </div>

    <footer><span>&copy; 2024 | </span> <span><a href="#">NYBB - SUST</a></span></footer>
</body>
</html>

templates/quiz4.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Issue 4</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="stylesheet" href="{% static 'quiz4.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <script src="{% static 'word-list.js' %}"></script>
    <style>
         h1{margin: 20px;}
        .score-board span{box-sizing:content-box;}
    </style>
</head>
<body>
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>
    <h2>Issue 4</h2>

    <div class="score-board" style="margin: 20px 0px;">
        <span>{{request.user}}</span>
        <span>Score: {{request.user.team.score}}</span>
    </div>

    <div class="clue" style="margin: 20px;">
        <div class="clue-1">
            <b>Warning:</b> The culprits are attempting to deceive you with a dirty trick. 
            They've arranged a Hangman game setup. Upon entering, your score is immediately decreased by 10. 
            Reloading the page will result in a further deduction of 10 points. 
            Failing to answer any of the six questions will result in a person's death, necessitating a restart.
            Will you outsmart the traps laid before you and continue your quest unscathed?
        </div>
    </div>
    <div class="game-modal">
        <div class="content">
            <img src="{% static 'images/victory.gif' %}">
            <h4>Game Over!</h4> <br>
            <button class="play-again">Play Again</button><br>

            <form action="{% url 'quiz4' %}" method="post" class="click-me"> {% csrf_token %}
                <input type="text" name="UnlockKey" placeholder="Unlock Key: 1953"> 
                {% if request.user.team.quiz_4_status == False %}
                    <button type="submit" class="button button-green">Submit</button>
                {% else %}
                    <button type="submit" class="button button-black" disabled>Submit</button>
                {% endif %}
            </form>
        </div>
    </div>
    <div style="display: flex; justify-content: center;">
        <div class="container">
            <div class="hangman-box">
                <img src="" draggable="false" alt="hangman-img">
                <h1>Hangman Game</h1>
            </div>
            <div class="game-box">
                <ul class="word-display"></ul>
                <h4 class="hint-text">Hint <b></b></h4>
                <h4 class="guesses-text">Incorrect guesses: <b></b></h4>
                <div class="keyboard"></div>
            </div>
        </div>
    </div>

    <div class="status">
        {% if request.user.team.quiz_4_status == False %}
            <span>Issue 4: Unsolved</span>
        {% else %}
            <span>Issue 4: Solved</span>
            <a href="{% url 'quiz5' %}" class="button button-green">Issue 5</a>
        {% endif %}
    </div>

    <footer><span>&copy; 2024 | </span> <span><a href="#">NYBB - SUST</a></span></footer>

  <script>
        // Define the URLs for images using Django template syntax
        const hangmanImageURLs = [
            "{% static 'images/hangman-0.svg' %}",
            "{% static 'images/hangman-1.svg' %}",
            "{% static 'images/hangman-2.svg' %}",
            "{% static 'images/hangman-3.svg' %}",
            "{% static 'images/hangman-4.svg' %}",
            "{% static 'images/hangman-5.svg' %}",
            "{% static 'images/hangman-6.svg' %}"
        ];
    
        // Initialize other constants
        const wordDisplay = document.querySelector(".word-display");
        const guessesText = document.querySelector(".guesses-text b");
        const keyboardDiv = document.querySelector(".keyboard");
        const hangmanImage = document.querySelector(".hangman-box img");
        const gameModal = document.querySelector(".game-modal");
        const playAgainBtn = gameModal.querySelector("button");
    
        // Initializing game variables
        let currentWordIndex = 0;
        let correctLetters, wrongGuessCount;
        const maxGuesses = 6;
    
        const resetGame = () => {
            // Resetting game variables and UI elements
            correctLetters = [];
            wrongGuessCount = 0;
            hangmanImage.src = hangmanImageURLs[0]; // Set initial hangman image
            guessesText.innerText = `${wrongGuessCount} / ${maxGuesses}`;
            const currentWord = wordList[currentWordIndex];
            wordDisplay.innerHTML = currentWord.word.split("").map(() => `<li class="letter"></li>`).join("");
            document.querySelector(".hint-text b").innerText = currentWord.hint;
            keyboardDiv.querySelectorAll("button").forEach(btn => btn.disabled = false);
            gameModal.classList.remove("show");
        };
    
        const victoryImageURL = "{% static 'images/victory.gif' %}";
        const lostImageURL = "{% static 'images/lost.gif' %}";
    
        const gameOver = (isVictory) => {
            if (isVictory) {
                gameModal.querySelector("img").src = victoryImageURL;
                gameModal.querySelector("h4").innerText = 'Congrats! Key: 1953';
            } else {
                gameModal.querySelector("img").src = lostImageURL;
                gameModal.querySelector("h4").innerText = 'Game Over!';
                // Decrease the score by 10
                const scoreElement = document.querySelector('.score-board span:nth-child(2)');
                const currentScore = parseInt(scoreElement.innerText.split(': ')[1]);
                const newScore = currentScore - 10;
                scoreElement.innerText = `Score: ${newScore}`;
                // Update the score on the server
                fetch("{% url 'update_score' %}", {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({ newScore: newScore })
                })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Failed to decrease score');
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                    // Handle error here
                });
            }
            gameModal.classList.add("show");
            
            if (isVictory) {
                playAgainBtn.style.display = "none";
                document.querySelector(".click-me").style.display = "flex";
            } else {
                playAgainBtn.style.display = "inline-block";
                document.querySelector(".click-me").style.display = "none";
            }
        };
    
        const initGame = (button, clickedLetter) => {
            // Checking if clickedLetter exists in the currentWord
            const currentWord = wordList[currentWordIndex];
            if (currentWord.word.includes(clickedLetter)) {
                // Showing all correct letters on the word display
                [...currentWord.word].forEach((letter, index) => {
                    if (letter === clickedLetter) {
                        correctLetters.push(letter);
                        wordDisplay.querySelectorAll("li")[index].innerText = letter;
                        wordDisplay.querySelectorAll("li")[index].classList.add("guessed");
                    }
                });
            } else {
                // If clicked letter doesn't exist then update the wrongGuessCount and hangman image
                wrongGuessCount++;
                hangmanImage.src = hangmanImageURLs[wrongGuessCount];
            }
            button.disabled = true; // Disable the clicked button so user can't click again
            guessesText.innerText = `${wrongGuessCount} / ${maxGuesses}`;
    
            // Call gameOver function if any of these conditions are met
            if (wrongGuessCount === maxGuesses) return gameOver(false);
            if (correctLetters.length === currentWord.word.length) {
                currentWordIndex++;
                if (currentWordIndex < wordList.length) {
                    resetGame();
                } else {
                    return gameOver(true);
                }
            }
        };
    
        // Creating keyboard buttons and adding event listeners
        for (let i = 97; i <= 122; i++) {
            const button = document.createElement("button");
            button.innerText = String.fromCharCode(i);
            keyboardDiv.appendChild(button);
            button.addEventListener("click", (e) => initGame(e.target, String.fromCharCode(i)));
        }
        for (let i = 48; i <= 57; i++) {
            const button = document.createElement("button");
            button.innerText = String.fromCharCode(i);
            keyboardDiv.appendChild(button);
            button.addEventListener("click", (e) => initGame(e.target, String.fromCharCode(i)));
        }

        // Initialize the game
        resetGame(); 
        playAgainBtn.addEventListener("click", () => {
            currentWordIndex = 0;
            resetGame();
        });
  </script>

</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Sign Up</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="stylesheet" href="{% static 'signin.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>


<body>
    <a href="{% url 'index' %}"><img src="{% static 'nybb-logo.webp' %}" alt="NYBB Logo" class="logo"></a>
    <h1>Genetic Odyssey</h1>
    <h2>Sign Up</h2>


    <form method="post">
        {% csrf_token %}

        <label for="id_full_name">Full Name</label>
        {{ form.full_name }}


        <label for="id_email">Email</label>
        {{ form.email }}

        <button type="submit" class="btn btn-primary">Register</button>
        <a href="{% url 'signin' %}" class="button button-green">Sign In</a>
    </form>
        
        {% if form.errors %}
            <div class="error-messages">
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

    <footer><span>&copy; 2024 | </span> <span><a href="https://soash.github.io/">NYBB - SUST</a></span></footer> 
</body>
</html>